### ISSUE TITLE
Dispose page controller

### ISSUE THREAD

**Issue by mr7ssam** [Baseflow/flutter_wizard#1]
Thanks for this great package

I need to implement copy in `WizardControllerImpl` 
In `didUpdateWidget` method.

Why?? Disposing page controller lead to an error when using expandable_pageview, calling after being disposed.

```
 ​  ​@override 
 ​  ​void​ ​didUpdateWidget​( 
 ​    ​covariant​ ​DefaultWizardController​ oldWidget, 
 ​  ) { 
 ​    ​// TODO: improve to copy with 
 ​    controller.​dispose​(); 
 ​    ​_createController​(); 
 ​    ​super​.​didUpdateWidget​(oldWidget); 
 ​  }
```

I noticed there is a Todo in `didUpdateWidget`
So i opened this issue for discussing before pull request 😅

**Comment by jopmiddelkamp** [comment]
Hi @Husssam12, sorry for my late response. Not sure if it still helps you but I've updated the  the controller with a `copyWith` method. Could you let me know if it solves your problem?

**Comment by mr7ssam** [comment]
> Hi @Husssam12, sorry for my late response. Not sure if it still helps you but I've updated the the controller with a `copyWith` method. Could you let me know if it solves your problem?

I use my forked repo, but this fix is better 
Thanks for this, I will close  this issue
